os:
  - linux

dist: bionic

language: python
python:
  - 3.7

services:
  - mysql
  - redis

install: pip install -r backend/requirements.txt

jobs:
  include:
    - stage: build
      script:
        # login to github registry
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin ghcr.io
        # build image
        - docker build -t PyMatchaAPI .
        # push image
        - docker push PyMatchaAPI
    - stage: test
      script:
        # login to github registry
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin ghcr.io
        # pull images
        - docker pull PyMatchaAPI
        # run docker on port 80
        # do not forget to add env-file an environment file in Settings/CI CD/Variables
        - docker run -d -p 5000:5000 --restart always PyMatchaAPI
        # run newman tests
        - newman run --color on 'PyMatcha.postman_collection.json'
      after_script:
        # stop and remove docker to prevent them from block port at next iteration/test
        - docker stop $(docker ps -a -q)
        - docker rm $(docker ps -a -q)
    - stage: lint
      script: black --check backend

notifications:
  email:
    recipients:
      - jlasne@student.42.fr
      - gmorer@student.42.fr
    on_success: change
    on_failure: always
