version: '3.3'

services:
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: pymatcha
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    env_file:
      - .env
#    ports:
#      - '3306:3306'
#    expose:
#      - '3306'
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - mysql-net
    healthcheck:
      test: "/usr/bin/mysql --user=$DB_USER --password=$DB_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5

  redis:
    container_name: redis
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - '6379:6379'
    networks:
      - redis-net
    volumes:
      - redis-data:/data

  workers:
    container_name: workers
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DB_PORT=3306
      - DB_HOST=mysql
    env_file:
      - .env
    entrypoint: celery worker --workdir . -A PyMatcha.celery -B --loglevel=info
    volumes:
      - backend:/backend
    depends_on:
      - redis
      - mysql
    links:
      - redis
    networks:
      - redis-net
      - mysql-net
    restart: always

  backend:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_DEBUG=true
      - DB_PORT=3306
      - DB_HOST=mysql
    ports:
      - "8080:5000"
    volumes:
      - backend:/backend
    depends_on:
      - mysql
      - redis
      - workers
    links:
      - mysql
      - redis
      - workers
    networks:
      - redis-net
      - mysql-net

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/frontend'
      - '/frontend/node_modules'
    ports:
      - '4242:8080'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80
    networks:
      - mysql-net

  swagger_ui:
    container_name: docs
    environment:
    - API_URL=/swagger.yaml
    image:   "swaggerapi/swagger-ui"
    volumes: ["./backend/schemas/swagger.yaml:/usr/share/nginx/html/swagger.yaml"]
    restart: always
    ports:   ["9000:8080"]

networks:
  redis-net:
  mysql-net:

volumes:
  redis-data:
  mysql:
  backend:
